// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiiFQrXVVuSVojoQZNlBizceTSwEsHlXo',
    appId: '1:483573878731:web:7b0fa89cb447f00cdfb04e',
    messagingSenderId: '483573878731',
    projectId: 'registrationapp-74683',
    authDomain: 'registrationapp-74683.firebaseapp.com',
    storageBucket: 'registrationapp-74683.appspot.com',
    measurementId: 'G-P8TFZELL4W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9IZNv8WuZd28sPaSre9lmvHRSE7Uzr-4',
    appId: '1:483573878731:android:a42e6b85466a9008dfb04e',
    messagingSenderId: '483573878731',
    projectId: 'registrationapp-74683',
    storageBucket: 'registrationapp-74683.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDC6xWDtxOeA_-yVUose95qhTQL9ZMRCqw',
    appId: '1:483573878731:ios:81609d0bd7b1efe3dfb04e',
    messagingSenderId: '483573878731',
    projectId: 'registrationapp-74683',
    storageBucket: 'registrationapp-74683.appspot.com',
    iosBundleId: 'com.babyboomer.registrationapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDC6xWDtxOeA_-yVUose95qhTQL9ZMRCqw',
    appId: '1:483573878731:ios:81609d0bd7b1efe3dfb04e',
    messagingSenderId: '483573878731',
    projectId: 'registrationapp-74683',
    storageBucket: 'registrationapp-74683.appspot.com',
    iosBundleId: 'com.babyboomer.registrationapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiiFQrXVVuSVojoQZNlBizceTSwEsHlXo',
    appId: '1:483573878731:web:77576dd171e9e452dfb04e',
    messagingSenderId: '483573878731',
    projectId: 'registrationapp-74683',
    authDomain: 'registrationapp-74683.firebaseapp.com',
    storageBucket: 'registrationapp-74683.appspot.com',
    measurementId: 'G-RNWP10SGP3',
  );
}
